- В шаге 1 мы добавляем блок finally после блоков catch.
Блок finally выполняется независимо от того, происходит или нет исключение в блоках try и catch.
- В шаге 2, при выполнении программы, блок finally всегда будет выполняться после выполнения блока
try или catch. Независимо от того, возникло исключение или нет, программа завершится, и в консоли будет
выведено сообщение "Program execution completed.". Это новое поведение, которое позволяет нам добавить код,
который должен быть выполнен независимо от возникновения исключений.