- В шаге 1 мы добавляем новый пункт catch перед другими пунктами catch,
чтобы перехватить общее исключение класса Exception. Это позволит нам обрабатывать любое исключение,
которое не было перехвачено предыдущими пунктами catch.
- В шаге 2, если во время выполнения программы возникает исключение, которое не перехватывается более
специфичными блоками catch, будет выбран блок catch с исключением класса Exception. В этом случае будет
выведено сообщение "An error occurred". Это новое поведение программы, которое позволяет перехватывать и
обрабатывать общие ошибки, не определенные явно в других пунктах catch.